CREATE DATABASE MUEBLES;
USE MUEBLES;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA BIGINT PRIMARY KEY auto_increment,
    NOMBRE_CATEGORIA VARCHAR(50)
);

CREATE TABLE ESTANTE(
	ID_ESTANTE BIGINT PRIMARY KEY auto_increment,
    PASILLO INT
);

CREATE TABLE PIEZAS(
    ID_PIEZA BIGINT PRIMARY KEY auto_increment,
    NOMBRE_PIEZA VARCHAR(50),
    ID_ESTANTE BIGINT,
    FOREIGN KEY (ID_ESTANTE) REFERENCES ESTANTE(ID_ESTANTE)
);

CREATE TABLE MUEBLES(
    ID_MUEBLE BIGINT PRIMARY KEY auto_increment,
    NOMBRE_MUEBLE VARCHAR(50),
    PRECIO_MUEBLE INT,
    ID_CATEGORIA BIGINT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE MUEBLE_PIEZA(
    ID_MUEBLE BIGINT,
    ID_PIEZA BIGINT,
    PRIMARY KEY(ID_MUEBLE,ID_PIEZA),
    FOREIGN KEY (ID_MUEBLE) REFERENCES MUEBLES(ID_MUEBLE),
    FOREIGN KEY (ID_PIEZA) REFERENCES PIEZAS(ID_PIEZA)
);